/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lockdown.traveller;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import static lockdown.traveller.jdbc.getConnection;

/**
 *
 * @author Lenovo
 */
public class find_train extends javax.swing.JFrame {
    
    private ArrayList<String> alltrains;
    private static int index;

    /**
     * Creates new form find_train
     */
    public find_train() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        start = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        end = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        train_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        distance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        find = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        add_stations = new javax.swing.JButton();
        add_trains = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Find Train");

        start.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("To");

        end.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        end.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        end.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Train Name");

        train_name.setEditable(false);
        train_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Distance(in Km)");

        distance.setEditable(false);
        distance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Time(in minutes)");

        time.setEditable(false);
        time.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stations"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        prev.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        prev.setText("prev");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        next.setText("next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        find.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        find.setText("find train");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        add_stations.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_stations.setText("Add Stations");
        add_stations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_stationsActionPerformed(evt);
            }
        });

        add_trains.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_trains.setText("Add Trains");
        add_trains.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_trainsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(train_name)
                    .addComponent(distance)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(find)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prev)
                        .addGap(304, 304, 304)
                        .addComponent(next)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(add_stations, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(add_trains, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addComponent(find)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(add_trains)
                    .addComponent(add_stations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(train_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prev)
                    .addComponent(next))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        // TODO add your handling code here:
         try{
            Connection con=getConnection();
            PreparedStatement statement=con.prepareStatement("SELECT * FROM station WHERE name !='"+end.getSelectedItem().toString()+"'");
            ResultSet result=statement.executeQuery();
            
            start.removeAllItems();
           start.addItem("select");
            while(result.next())
            {
                
                
                start.addItem(result.getString("name"));
               
                
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_startMouseClicked

    private void endMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endMouseClicked
        // TODO add your handling code here:
        try{
            Connection con=getConnection();
            PreparedStatement statement=con.prepareStatement("SELECT * FROM station WHERE name !='"+start.getSelectedItem().toString()+"'");
            ResultSet result=statement.executeQuery();
            
            end.removeAllItems();
           end.addItem("select");
            while(result.next())
            {
                
                
                end.addItem(result.getString("name"));
               
                
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_endMouseClicked

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        
        
        alltrains=station_db.findtrain(start.getSelectedItem().toString(), end.getSelectedItem().toString());
        //System.out.println(alltrains);
        index=0;
        if(alltrains.size()!=0)
        {
            ArrayList<String> allstations=station_db.findtrainroot(alltrains.get(index));
            ArrayList<String> arr=station_db.finddadicatedroot(allstations, start.getSelectedItem().toString(), end.getSelectedItem().toString());
            train_name.setText(alltrains.get(index));
            distance.setText(String.valueOf(station_db.finddistance(arr)));
            time.setText(String.valueOf(station_db.findtime(arr)));
            jTable1.setModel(new DefaultTableModel(null,new String[]{"Stations"}));
            DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
            ArrayList<String> array=new ArrayList<String>();
            for(int i=0;i<arr.size();i++)
            {
                array.add(arr.get(i).toString());
                model1.addRow(array.toArray());
                array.clear();
            }
        }
        else
        {
            train_name.setText("");
            distance.setText("");
            time.setText("");
            jTable1.setModel(new DefaultTableModel(null,new String[]{"Stations"}));
        }
        
    }//GEN-LAST:event_findActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        // TODO add your handling code here:
        if(index>0)
        {
            index--;
            ArrayList<String> allstations=station_db.findtrainroot(alltrains.get(index));
            ArrayList<String> arr=station_db.finddadicatedroot(allstations, start.getSelectedItem().toString(), end.getSelectedItem().toString());
            train_name.setText(alltrains.get(index));
            distance.setText(String.valueOf(station_db.finddistance(arr)));
            time.setText(String.valueOf(station_db.findtime(arr)));
            jTable1.setModel(new DefaultTableModel(null,new String[]{"Stations"}));
            DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
            ArrayList<String> array=new ArrayList<String>();
            for(int i=0;i<arr.size();i++)
            {
                array.add(arr.get(i).toString());
                model1.addRow(array.toArray());
                array.clear();
            }
        }
    }//GEN-LAST:event_prevActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        if(index<alltrains.size()-1)
        {
            index++;
            ArrayList<String> allstations=station_db.findtrainroot(alltrains.get(index));
            ArrayList<String> arr=station_db.finddadicatedroot(allstations, start.getSelectedItem().toString(), end.getSelectedItem().toString());
            train_name.setText(alltrains.get(index));
            distance.setText(String.valueOf(station_db.finddistance(arr)));
            time.setText(String.valueOf(station_db.findtime(arr)));
            jTable1.setModel(new DefaultTableModel(null,new String[]{"Stations"}));
            DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
            ArrayList<String> array=new ArrayList<String>();
            for(int i=0;i<arr.size();i++)
            {
                array.add(arr.get(i).toString());
                model1.addRow(array.toArray());
                array.clear();
            }
        }
    }//GEN-LAST:event_nextActionPerformed

    private void add_trainsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_trainsActionPerformed
        // TODO add your handling code here:
        add_train newdisplay=new add_train();
                newdisplay.setVisible(true);
                newdisplay.pack();
                newdisplay.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_add_trainsActionPerformed

    private void add_stationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_stationsActionPerformed
        // TODO add your handling code here:
        add_station newdisplay=new add_station();
                newdisplay.setVisible(true);
                newdisplay.pack();
                newdisplay.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_add_stationsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        login reg=new login();
                reg.setVisible(true);
                reg.pack();
                reg.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(find_train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(find_train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(find_train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(find_train.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new find_train().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_stations;
    private javax.swing.JButton add_trains;
    private javax.swing.JTextField distance;
    private javax.swing.JComboBox<String> end;
    private javax.swing.JButton find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout;
    private javax.swing.JButton next;
    private javax.swing.JButton prev;
    private javax.swing.JComboBox<String> start;
    private javax.swing.JTextField time;
    private javax.swing.JTextField train_name;
    // End of variables declaration//GEN-END:variables
}
